apiVersion: v1
kind: Pod
metadata:
  name: alpine-curl-pod-4
  namespace: dev
  labels:
    app: alpine-curl-4
spec:
  containers:
  - name: alpine-curl-container
    image: alpine:3.20
    command: ["/bin/sh", "-c", "apk update && apk add curl && sleep infinity"]