apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod-purple
  labels:
    app: color-api-app-purple
spec:
  containers:
    - name: color-api-container
      image: selcouthonism/color-api-image:1.3.0
      envFrom:
        - configMapRef:
            name: color-api-config-purple-as-env-variable
      volumeMounts:
        - name: color-api-config-volume # Must match the volume name below
          mountPath: /mnt/config
          readOnly: true
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: color-api-config-volume
      configMap:
        name: color-api-config-purple-as-file