apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-secret-via-volume-item
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: db-credentials
      mountPath: /etc/db
      readOnly: true
  volumes:
  - name: db-credentials
    secret:
      secretName: db-creds # Name of the Secret to mount
      items: # Specify which keys to mount
      - key: password 
        path: dev/password # Mount 'password' key to 'dev/password' file