apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-secret-as-env-vars
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo DB User is $DB_USER; echo DB Password is $DB_PASSWORD; sleep 3600"]
    #command: ["sh", "-c", "echo DB User is $username; echo DB Password is $password; sleep 3600"] # If using envFrom
    #envFrom: # Load all keys from the secret as environment variables
    #  - secretRef:
    #      name: db-creds
    env:
    - name: DB_USER # # Maps to application property
      valueFrom:
        secretKeyRef:
          name: db-creds # Name of the secret
          key: username # Key in the secret
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: password
  restartPolicy: Never