apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-restricted
spec:
  containers:
  - name: nginx-container
    image: nginxinc/nginx-unprivileged:1.27.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
    - containerPort: 80
    securityContext:
      runAsNonRoot: true
      #runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault