apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  resources:
    requests:
      storage: 1Gi
      #storage: 4Gi # must be less than or equal to the PV size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage # must match the storageClassName of the PV