apiVersion: v1
kind: Pod
metadata:
  name: alpine-curl-pod
  namespace: dev
  labels:
    app: alpine-curl
spec:
  serviceAccountName: pod-inspector # Use the ServiceAccount defined in sa-pod-inspector-ns-dev.yaml
  containers:
  - name: alpine-curl-container
    image: alpine:3.20
    command: ["/bin/sh", "-c", "apk update && apk add curl && sleep infinity"]