apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: alice-csr
spec:
  # cat alice.csr | base64 | tr -d "\n"
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU9NQXdHQTFVRUF3d0ZZV3hwWTJVeERqQU1CZ05WQkFvTUJXRmtiV2x1TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcWxIejF2RkUzWkd1dEhvVE5nMXZWd2dvCm9hZ2lDM2VWRDZKdk1aWFFKU0k5bk1xdnhPaVhNMzQvWFc0b2dXOHlvY2RqTkxVdURZUkpPTHVmdFF3MGJsU20KWGtNWVUxekV1WnVpZGlzRU1pTHo3QjFSN3hrTnVEcjZrQ052UmIwRGVMS09wOUUzRHVybmkxN1RaL0xXcTN2Vgo3cnM5RDZHUm9rTENsMGJ0OWpZVnVDbXZTYWxQaFA3SGNrcUZqcVE2Ui9EaVhLWE9tYkhRQjZWOUNhaXFLQm9kCllTL3R0OVJPR29LeTgrTlVsZGJxYVJQZ0xoSTlwVnZJdnJIWGExTHVUS3c0eENNTHViencwQnlqSHU0V1Y0clkKWGpUSms5QTJQcmlmZ29pYlBFNXlOY2RBYTFrMXNYb05KOCtLa3hKUTFaaGZRK2JmaUNlT3M3T1FZbFhCeFFJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGRHlweFZ3ZXNxV1hKNXJ0U2l6Mng2a3I1ZFRDU3FaClNBcUVCZDFKYVZzOVlXTDhZVDIzM2hsRXNoWHBBUDhvdmNhSGlWanpnR3M1UGFia0UvK1BhY0luMnRaVzdZc1oKRmJVREdKU2NOallaZE1KcjB1b05rc0hnL0pkOXYzdWFRb2hYRnlGM29iempZam9pYW9rMS94aTF5YmVEUDUyTApKUVp2amlMaHJaOFF2a21NQmE5QVp5Z2czamhmMzI3bmFvSjZOTVdQSkg5UHJlc29keVh3SURZaHp5MjNDc3hrCmk4dUQrYkFrd0U4OGMxZXd2RCtpRGUwQ3krOFJwWVJiNG1YVTF4Y3F1dmNjKzFNOUtDeWszbHBTZUVZMm0zUHYKY2Zpd1RjSTF5WVE4TXdNN0tyWjVCQ2xIOUM0NkEyNUdGSmhkVERQNm5YSWpRaFlsTHJmWDZEOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
  - client auth

---

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  # cat bob.csr | base64 | tr -d "\n"
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1lUQ0NBVWtDQVFBd0hERU1NQW9HQTFVRUF3d0RZbTlpTVF3d0NnWURWUVFLREFOa1pYWXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzZnWTJBTDE0NFprMm45ekZoSFIzM21NaVZEcENICjdkMkR2K1hMZUVkVzVQVExpUVladEMxZTN0SnR6YWJad3dPb1Q0VExWZ3ZDRm8rTG1DSVpUaTFOKzZqMFg0bEwKc0NSdCsrSzh1TTloaG1Wdk9mc0R4RkRqRFNzaG5kZUliYWlTNU9MTHpOU2dkZVcrSkRhSW9NRGxvZGY3MXlvUApmZXBCSVU1dFpGVFN1bWRIMitwQmVCOFg1WVJDTndqcTg0WjNBS0Zvak52aWY2WWhDclgyVmRycjBuVXhuODR5CkVjSkNxaTFEWVhoZXdqT25PdVRDRFlsaWRZR0dxZng4M3BQeGVnUW1oajhiY0hzc3VGSDdkV1gyV05ibElYbHIKd1dyS1JnRnJLTlJ4WjdZQVdvQis5eVQ5ZjBPZzJDSkNBOFdkeUZtTVBYcWRaMCtKbGROb2ErdFJBZ01CQUFHZwpBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBTkNFWlFVMzhyVFpKOHJEd2dMR2o3dVgxZHpoZnY0RGIzMDkzCkZKK3BwWmFOZnIzTC9NdGxOZzBOVE0yQmRpSXFCMXdlenBtK2JEV1BlQnl6V3lSenRNMExGcjNweUhieWhJYkMKajhWUldRaFJIck0rRTNDN1VwQ2tZZmtPMGZUbk9sZlFHYUl3V0I5bnIrR3FoSzVEOGJyNkJRblY0M1BicFFZNgp3Sm8zR25OVG50UlhmRWppSFp0eG5DdVFFaVBVc29hS1UwRkY2bUtjc2JwcEw3Wi9kQWRKTEZtYXlSUUdlZGU3CmJza1BVT0hXN2Q2VWdHYzVpd1RIcDdGMEN3b2FvNnRoZWJESWw4aThZNXlQSHhidHZ2SmdxcExabytzc0FxRnEKSWJKTnVMUDhXaVIrVVN1MHJBbnREeHdzK2UrOWpudGp6MnVlc1lMMmlrZ0pmdFo2MkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
  - client auth