apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
    environment: local
    tier: backend
spec:
  containers:
    - name: color-api
      image: selcouthonism/color-api-image:1.1.0
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: color-frontend
  labels:
    app: color-api
    environment: local
    tier: frontend
spec:
  containers:
    - name: color-nginx
      image: nginx:latest
      ports:
        - containerPort: 80