apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  namespace: dev
  labels:
    app: color-api-pod
spec:
  containers: 
    - name: color-api-container
      image: selcouthonism/color-api-image:1.2.1
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: DELAY_STARTUP
          value: "false"
        - name: FAIL_LIVENESS
          value: "false"
        - name: FAIL_READINESS
          value: "false"
      startupProbe:
        httpGet:
          path: /up
          port: 80
        failureThreshold: 2
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 2
        periodSeconds: 5