apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: selcouthonism/color-api-image:1.1.0
      ports:
        - containerPort: 80