apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  namespace: dev
  labels:
    app: heavy-api
spec:
  containers:
    - name: heavy-api
      image: selcouthonism/color-api-image:1.1.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1"        # Request 1 CPU core
          memory: "1Gi"    # Request 1Gi memory
        limits:
          cpu: "2"        # Limit to 2 CPU cores
          memory: "2Gi"    # Limit to 2Gi memory