apiVersion: v1
kind: Service
metadata:
  name: color-api-svc-nodeport
  labels:
    app: color-api
spec:
  type: NodePort
  selector:
    app: color-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007