# For documrentation, equivalent to the imperative command:
# kubectl expose pod nginx-pod --type=NodePort --name=nginx-svc --port=80 --target-port=80
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx